[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = [
    "h5py",
    "faiss",
    "scipy.sparse",
    "scipy.sparse.linalg",
    "pandas",
    "open_clip",
    "torchvision",
    "torchvision.datasets"
]
ignore_missing_imports = true

[tool.pyright]
reportGeneralTypeIssues = false