defaults:
  - _self_
  - dataset: cifar10
  - model: dino_vit_S14
  - override hydra/hydra_logging: rich_logger
  - override hydra/job_logging: rich_logger


split: "both"  # "train" | "test" | "both"


dataloader:
  batch_size: 64
  num_workers: 16
  shuffle: false
  pin_memory: true

  # params for hydra.utils.instantiate
  _target_: torch.utils.data.DataLoader
  _partial_: true


trainer:
  precision: "16-mixed"

  # params for hydra.utils.instantiate
  _target_: pytorch_lightning.Trainer
  accelerator: "gpu"
  devices: 1
  logger: false


# sweep over combinations of datasets and models
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      dataset: 
        aircraft,
        cars,
        cifar10,
        cifar100,
        domainnetreal,
        dtd,
        flowers,
        food101,
        imagenet100,
        pets,
        places365,
        svhn,
        amyloid_beta_bal,
        amyloid_beta_unbal,
        blood_smear,
        cell_cycle,
        colon_polyps,
        colorectal_histology,
        diabetic_retinopathy,
        ham10000,
        heart_failure,
        iicbu_hela,
        iicbu_lymphoma,
        malaria,
        pap_smear_2018,
        pap_smear_2019,
        patch_camelyon,
        pollen
      model:
        openclip_vit_B16,
        openclip_vit_L14,
        openclip_vit_H14,
        openclip_vit_g14,
        openclip_vit_G14,
        dino_vit_S14,
        dino_vit_B14,
        dino_vit_L14,
        dino_vit_g14

  # disable hydra logging
  run:
    dir: ""
  sweep:
    dir: /tmp/${oc.env:USER}/multirun
  job:
    chdir: false
  output_subdir: null
  